/**
 * ARCHITECTURE.md section 77: canonical (English) book id -> the exact key
 * `data/fra_lsg.json` uses for that book. Deliberately its own table, not
 * a reuse of `FRENCH_BOOK_ALIASES` (regex-detector.ts) or the French
 * display-name tables (overlay.js/dashboard.js, section 72.3) — this
 * bundled dataset's own key format doesn't match either: no space before
 * a numeral prefix ("1samuel", not "1 samuel") and a shorter key for Song
 * of Solomon ("cantique", not "cantique des cantiques"). Verified directly
 * against the file's own top-level keys before writing this, not assumed
 * from the other two tables' conventions.
 */
export const OFFLINE_BIBLE_BOOK_KEYS: Readonly<Record<string, string>> = {
  genesis: "genese",
  exodus: "exode",
  leviticus: "levitique",
  numbers: "nombres",
  deuteronomy: "deuteronome",
  joshua: "josue",
  judges: "juges",
  ruth: "ruth",
  "1 samuel": "1samuel",
  "2 samuel": "2samuel",
  "1 kings": "1rois",
  "2 kings": "2rois",
  "1 chronicles": "1chroniques",
  "2 chronicles": "2chroniques",
  ezra: "esdras",
  nehemiah: "nehemie",
  esther: "esther",
  job: "job",
  psalm: "psaumes",
  proverbs: "proverbes",
  ecclesiastes: "ecclesiaste",
  "song of solomon": "cantique",
  isaiah: "esaie",
  jeremiah: "jeremie",
  lamentations: "lamentations",
  ezekiel: "ezechiel",
  daniel: "daniel",
  hosea: "osee",
  joel: "joel",
  amos: "amos",
  obadiah: "abdias",
  jonah: "jonas",
  micah: "michee",
  nahum: "nahum",
  habakkuk: "habacuc",
  zephaniah: "sophonie",
  haggai: "aggee",
  zechariah: "zacharie",
  malachi: "malachie",
  matthew: "matthieu",
  mark: "marc",
  luke: "luc",
  john: "jean",
  acts: "actes",
  romans: "romains",
  "1 corinthians": "1corinthiens",
  "2 corinthians": "2corinthiens",
  galatians: "galates",
  ephesians: "ephesiens",
  philippians: "philippiens",
  colossians: "colossiens",
  "1 thessalonians": "1thessaloniciens",
  "2 thessalonians": "2thessaloniciens",
  "1 timothy": "1timothee",
  "2 timothy": "2timothee",
  titus: "tite",
  philemon: "philemon",
  hebrews: "hebreux",
  james: "jacques",
  "1 peter": "1pierre",
  "2 peter": "2pierre",
  "1 john": "1jean",
  "2 john": "2jean",
  "3 john": "3jean",
  jude: "jude",
  revelation: "apocalypse",
}
