// GENERATED by a one-off script from PyPI / python.org / Hugging Face metadata.
// Every artifact is pinned to an exact URL and SHA-256; the installer refuses anything else.
// To upgrade: re-resolve (pip download --platform win_amd64 --python-version 3.12 --only-binary=:all:),
// recompute hashes, review the diff.

export type PinnedFile = { readonly url: string; readonly sha256: string; readonly size: number }

export const EMBEDDED_PYTHON: PinnedFile & { readonly version: string } = {
  version: "3.12.10",
  url: "https://www.python.org/ftp/python/3.12.10/python-3.12.10-embed-amd64.zip",
  sha256: "4acbed6dd1c744b0376e3b1cf57ce906f9dc9e95e68824584c8099a63025a3c3",
  size: 0,
}

export const FASTER_WHISPER_WHEELS: readonly (PinnedFile & { readonly file: string })[] = [
  {
    "file": "anyio-4.15.1-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/12/b8/4bd346e22b28902df4d651910f5242c28d84e4a5c2435ca5c3f797ed7e2e/anyio-4.15.1-py3-none-any.whl",
    "sha256": "6152fdbbf9a77fdec97731721bebf7c4c44f7c29b424b0065826173efc7ed101",
    "size": 132079
  },
  {
    "file": "av-19.0.1-cp312-abi3-win_amd64.whl",
    "url": "https://files.pythonhosted.org/packages/e6/dc/a87a5a5e3ac462734f9befd8bad1447301e5802d8c111e22bf708fba7af3/av-19.0.1-cp312-abi3-win_amd64.whl",
    "sha256": "906fc3db09288319a75ea23ffefb59961c7dbe0d1c074601507a89de7d8593d8",
    "size": 28149519
  },
  {
    "file": "certifi-2026.7.22-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/0b/a7/71ac2cff56fec219ed242bb11b8efb69fcc4bec75db06fb7bfe35de520e6/certifi-2026.7.22-py3-none-any.whl",
    "sha256": "62f22742b58a1a33014a2b6b706588a8d7e2a88ae7bd1a6ebe8c992928483775",
    "size": 136983
  },
  {
    "file": "click-8.5.0-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/58/50/6c0d534c5f134586a8e1ba4e330569e32f057e33372ae556463212fb4cd3/click-8.5.0-py3-none-any.whl",
    "sha256": "255bc9599cf7748b4b1a446ccc735421bd08a2ae529a8b88597d3de5664ee360",
    "size": 125251
  },
  {
    "file": "colorama-0.4.6-py2.py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl",
    "sha256": "4f1d9991f5acc0ca119f9d443620b77f9d6b33703e51011c16baf57afb285fc6",
    "size": 25335
  },
  {
    "file": "ctranslate2-4.8.2-cp312-cp312-win_amd64.whl",
    "url": "https://files.pythonhosted.org/packages/4e/23/e3b5322ff7368fcbed181ea4c209149416e7940b5b04971d5ee4084afe1a/ctranslate2-4.8.2-cp312-cp312-win_amd64.whl",
    "sha256": "d94421d565d0de61c032998f737a18942b0f2bef40c0424b1846ec6f67300105",
    "size": 19222069
  },
  {
    "file": "faster_whisper-1.2.1-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/05/99/49ee85903dee060d9f08297b4a342e5e0bcfca2f027a07b4ee0a38ab13f9/faster_whisper-1.2.1-py3-none-any.whl",
    "sha256": "79a66ad50688c0b794dd501dc340a736992a6342f7f95e5811be60b5224a26a7",
    "size": 1118909
  },
  {
    "file": "filelock-4.0.11-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/4a/4d/2983a9fc0a412a09151299d1ec9eb7511e3d577f7213e19395fabebf9db6/filelock-4.0.11-py3-none-any.whl",
    "sha256": "1cbdc4ace7fb11d2f6d073f5c3d91537a23b3d58d2bf2fdffc12c6d717a589c6",
    "size": 111688
  },
  {
    "file": "flatbuffers-25.12.19-py2.py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/e8/2d/d2a548598be01649e2d46231d151a6c56d10b964d94043a335ae56ea2d92/flatbuffers-25.12.19-py2.py3-none-any.whl",
    "sha256": "7634f50c427838bb021c2d66a3d1168e9d199b0607e6329399f04846d42e20b4",
    "size": 26661
  },
  {
    "file": "fsspec-2026.9.0-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/6c/c0/a98505f18594f1bce828bb159cec0fcf9860562f1a2c85913409fc8f3d9e/fsspec-2026.9.0-py3-none-any.whl",
    "sha256": "8dd6e646e99ea382bd85f97a45e6b526a442d79423a7dc673f1e2756d05fcb5f",
    "size": 221738
  },
  {
    "file": "h11-0.16.0-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/04/4b/29cac41a4d98d144bf5f6d33995617b185d14b22401f75ca86f384e87ff1/h11-0.16.0-py3-none-any.whl",
    "sha256": "63cf8bbe7522de3bf65932fda1d9c2772064ffb3dae62d55932da54b31cb6c86",
    "size": 37515
  },
  {
    "file": "hf_xet-1.6.0-cp38-abi3-win_amd64.whl",
    "url": "https://files.pythonhosted.org/packages/98/b7/8c59a66d15205024662f1d66968136f13893f96df1ddc5087e2e281fc95f/hf_xet-1.6.0-cp38-abi3-win_amd64.whl",
    "sha256": "fb4fadde1b2b70bf4c0c14a6dccbe7194b1c28947fefd5bbe3fed9d940676c3b",
    "size": 4033128
  },
  {
    "file": "httpcore-1.0.9-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/7e/f5/f66802a942d491edb555dd61e3a9961140fd64c90bce1eafd741609d334d/httpcore-1.0.9-py3-none-any.whl",
    "sha256": "2d400746a40668fc9dec9810239072b40b4484b640a8c38fd654a024c7a1bf55",
    "size": 78784
  },
  {
    "file": "httpx-0.28.1-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/2a/39/e50c7c3a983047577ee07d2a9e53faf5a69493943ec3f6a384bdc792deb2/httpx-0.28.1-py3-none-any.whl",
    "sha256": "d909fcccc110f8c7faf814ca82a9a4d816bc5a6dbfea25d6591d6985b8ba59ad",
    "size": 73517
  },
  {
    "file": "huggingface_hub-1.33.0-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/fc/16/963096d224b80909432dc16561a615fd33d2d13beef3ce4c63fa25e40867/huggingface_hub-1.33.0-py3-none-any.whl",
    "sha256": "04e434b06e100eddbce9a6e817d72693a7884b10a79bd67ab48080d5c07eb899",
    "size": 846435
  },
  {
    "file": "idna-3.20-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/58/a2/bb081bab032533a855d44de1d56f8e8426114ff1ba5d1f07a438a0a654f8/idna-3.20-py3-none-any.whl",
    "sha256": "ab7ae7122974553370f0bdb919e1a960b2cd1bc1ef0276416d896db81c14582c",
    "size": 69583
  },
  {
    "file": "numpy-2.5.3-cp312-cp312-win_amd64.whl",
    "url": "https://files.pythonhosted.org/packages/3c/a1/accf6d4f0c80c5d9ba9735d6b1550e444180599f34dec69ca01360f717ad/numpy-2.5.3-cp312-cp312-win_amd64.whl",
    "sha256": "0a59a421a32580a009e8a1751345bf829631b990dc1794b80514ab722b435def",
    "size": 12567828
  },
  {
    "file": "onnxruntime-1.30.0-cp312-cp312-win_amd64.whl",
    "url": "https://files.pythonhosted.org/packages/a6/13/0f1699f6de549c9324bc9112a2a85b14c517904cd11b562a654643b755a1/onnxruntime-1.30.0-cp312-cp312-win_amd64.whl",
    "sha256": "f3501472571f1b1eee50e017851e7929f5ea37312d2d8c2494a19e8fc58b4a38",
    "size": 14311470
  },
  {
    "file": "packaging-26.3-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/63/34/ba1c580383c9eada3711951fef0795c80b829a078d72188184bcab9dd527/packaging-26.3-py3-none-any.whl",
    "sha256": "d7193f7c8e4e93f444fde0262bf90af30e16fa0ad0ad44cb553c87339b23cd1c",
    "size": 129956
  },
  {
    "file": "protobuf-7.36.2-cp310-abi3-win_amd64.whl",
    "url": "https://files.pythonhosted.org/packages/8a/55/b77bda4e5e5f5971fb51b07663694690e9afdb9402136c16a522bd621cad/protobuf-7.36.2-cp310-abi3-win_amd64.whl",
    "sha256": "a300819d441e078a5608c0d3c709796bb548136058fda017ae51d425b44fd353",
    "size": 456514
  },
  {
    "file": "pyyaml-6.0.3-cp312-cp312-win_amd64.whl",
    "url": "https://files.pythonhosted.org/packages/86/bf/899e81e4cce32febab4fb42bb97dcdf66bc135272882d1987881a4b519e9/pyyaml-6.0.3-cp312-cp312-win_amd64.whl",
    "sha256": "5fcd34e47f6e0b794d17de1b4ff496c00986e1c83f7ab2fb8fcfe9616ff7477b",
    "size": 154003
  },
  {
    "file": "tokenizers-0.23.2-cp310-abi3-win_amd64.whl",
    "url": "https://files.pythonhosted.org/packages/db/f7/0a69ac6b82dbccf3f71add938a161c497952749294b8dd6dfe03a819dc40/tokenizers-0.23.2-cp310-abi3-win_amd64.whl",
    "sha256": "2e96f5699d5249c9c64aa8412e044f727aae3a4098cf830f9901ec1afc361cde",
    "size": 2863236
  },
  {
    "file": "tqdm-4.70.1-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/a7/03/921a3d3c75785aca9ebfbfcabfbc3a1be12e2ab5265deb026d55a5a3f83e/tqdm-4.70.1-py3-none-any.whl",
    "sha256": "c293e525e6fef9c20e8728fd4612df02a0aa31bb5fe91ecd93e123b1b7bffa73",
    "size": 80199
  },
  {
    "file": "typing_extensions-4.16.0-py3-none-any.whl",
    "url": "https://files.pythonhosted.org/packages/49/d3/b8441a820a491ddfc024b0b0cf0393375b75ea13866d9c66727e54c2fc80/typing_extensions-4.16.0-py3-none-any.whl",
    "sha256": "481caa481374e813c1b176ada14e97f1f67a4539ce9cfeb3f350d78d6370c2e8",
    "size": 45571
  }
]

export type FasterWhisperModelId = "small" | "base"

export const FASTER_WHISPER_MODELS: Readonly<
  Record<FasterWhisperModelId, { readonly revision: string; readonly files: readonly (PinnedFile & { readonly path: string })[] }>
> = {
  "small": {
    "revision": "536b0662742c02347bc0e980a01041f333bce120",
    "files": [
      {
        "path": "config.json",
        "url": "https://huggingface.co/Systran/faster-whisper-small/resolve/536b0662742c02347bc0e980a01041f333bce120/config.json",
        "sha256": "b55496ac7940a7ae47d2c01eab40edfd8701feec1229d9cce3b40014383fb828",
        "size": 2370
      },
      {
        "path": "model.bin",
        "url": "https://huggingface.co/Systran/faster-whisper-small/resolve/536b0662742c02347bc0e980a01041f333bce120/model.bin",
        "sha256": "3e305921506d8872816023e4c273e75d2419fb89b24da97b4fe7bce14170d671",
        "size": 483546902
      },
      {
        "path": "tokenizer.json",
        "url": "https://huggingface.co/Systran/faster-whisper-small/resolve/536b0662742c02347bc0e980a01041f333bce120/tokenizer.json",
        "sha256": "fb7b63191e9bb045082c79fd742a3106a12c99513ab30df4a0d47fa6cb6fd0ab",
        "size": 2203239
      },
      {
        "path": "vocabulary.txt",
        "url": "https://huggingface.co/Systran/faster-whisper-small/resolve/536b0662742c02347bc0e980a01041f333bce120/vocabulary.txt",
        "sha256": "34ce3fe1c5041027b3f8d42912270993f986dbc4bb34cf27f951e34a1e453913",
        "size": 459861
      }
    ]
  },
  "base": {
    "revision": "ebe41f70d5b6dfa9166e2c581c45c9c0cfc57b66",
    "files": [
      {
        "path": "config.json",
        "url": "https://huggingface.co/Systran/faster-whisper-base/resolve/ebe41f70d5b6dfa9166e2c581c45c9c0cfc57b66/config.json",
        "sha256": "56a6d8110d311f19c8f0471e562832c7527f146b567275bfca59fcf7c184da9a",
        "size": 2309
      },
      {
        "path": "model.bin",
        "url": "https://huggingface.co/Systran/faster-whisper-base/resolve/ebe41f70d5b6dfa9166e2c581c45c9c0cfc57b66/model.bin",
        "sha256": "d01c3014881c9c6f3133c182f3d2887eb6ca1c789a7538c5c007196857a0a6a9",
        "size": 145217532
      },
      {
        "path": "tokenizer.json",
        "url": "https://huggingface.co/Systran/faster-whisper-base/resolve/ebe41f70d5b6dfa9166e2c581c45c9c0cfc57b66/tokenizer.json",
        "sha256": "fb7b63191e9bb045082c79fd742a3106a12c99513ab30df4a0d47fa6cb6fd0ab",
        "size": 2203239
      },
      {
        "path": "vocabulary.txt",
        "url": "https://huggingface.co/Systran/faster-whisper-base/resolve/ebe41f70d5b6dfa9166e2c581c45c9c0cfc57b66/vocabulary.txt",
        "sha256": "34ce3fe1c5041027b3f8d42912270993f986dbc4bb34cf27f951e34a1e453913",
        "size": 459861
      }
    ]
  }
}
